In [1]:
import tensorflow as tf
import keras

print("TensorFlow version:", tf.__version__)
print("Keras version (via tf.keras):", tf.keras.__version__)
print("Standalone Keras version (if installed):", keras.__version__)
print("GPU Available:", tf.config.list_physical_devices('GPU'))

TensorFlow version: 2.10.0
Keras version (via tf.keras): 2.10.0
Standalone Keras version (if installed): 2.10.0
GPU Available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [2]:
import tensorflow as tf

tf.debugging.set_log_device_placement(True)

a = tf.constant([[1.0, 2.0]])
b = tf.constant([[3.0], [4.0]])
c = tf.matmul(a, b)

print("Result:", c)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op MatMul in device /job:localhost/replica:0/task:0/device:GPU:0
Result: tf.Tensor([[11.]], shape=(1, 1), dtype=float32)


In [1]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical

# 데이터 불러오기
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
y_train, y_test = to_categorical(y_train), to_categorical(y_test)

# 모델 구성
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# 학습 (1 에폭만 테스트용)
model.fit(x_train, y_train, epochs=1, batch_size=128, validation_split=0.1)

422/422 [==============================] - 2s 3ms/step - loss: 0.3795 - accuracy: 0.8955 - val_loss: 0.1696 - val_accuracy: 0.9563


In [3]:
import tensorflow as tf

# 예제 데이터: (1, 2, 3) == (batch=1, 2개 엔티티, 임베딩 차원=3)
v_embed = tf.constant([[[1., 2., 3.],
                        [4., 5., 6.]]])  # (1, 2, 3)

r_embed = tf.constant([[[10., 20., 30.],
                        [40., 50., 60.]]])  # (1, 2, 3)
# print(v_embed.shape)
# print(r_embed.shape)

# 차원 확장
v_expand = tf.expand_dims(v_embed, axis=2)  # (1, 2, 1, 3)
r_expand = tf.expand_dims(r_embed, axis=1)  # (1, 1, 2, 3)

print(v_expand)
# print(v_expand.shape)
# print(r_expand.shape)

# 타일 복제
v_tiled = tf.tile(v_expand, [1, 1, 2, 1])  # (1, 2, 2, 3)
r_tiled = tf.tile(r_expand, [1, 2, 1, 1])  # (1, 2, 2, 3)
print(v_tiled)

# 마지막 차원 기준으로 붙이기
pair_embed = tf.concat([v_tiled, r_tiled], axis=-1)  # (1, 2, 2, 6)

# 결과 확인
print("v_tiled:\n", v_tiled.numpy())
print("r_tiled:\n", r_tiled.numpy())
print("pair_embed:\n", pair_embed.numpy())


tf.Tensor(
[[[[1. 2. 3.]]

  [[4. 5. 6.]]]], shape=(1, 2, 1, 3), dtype=float32)
tf.Tensor(
[[[[1. 2. 3.]
   [1. 2. 3.]]

  [[4. 5. 6.]
   [4. 5. 6.]]]], shape=(1, 2, 2, 3), dtype=float32)
v_tiled:
 [[[[1. 2. 3.]
   [1. 2. 3.]]

  [[4. 5. 6.]
   [4. 5. 6.]]]]
r_tiled:
 [[[[10. 20. 30.]
   [40. 50. 60.]]

  [[10. 20. 30.]
   [40. 50. 60.]]]]
pair_embed:
 [[[[ 1.  2.  3. 10. 20. 30.]
   [ 1.  2.  3. 40. 50. 60.]]

  [[ 4.  5.  6. 10. 20. 30.]
   [ 4.  5.  6. 40. 50. 60.]]]]
